version: "3"
services:
 mymongodb:
   image: mongo:latest
   container_name: "mymongodb"
   ports:
     - 27017:27017
 linhaonibus-ms:
   image: linhaonibus-ms:1.0
   container_name: linhaonibus-ms
   ports:
     - 8080:8080
   links:
     - mymongodb  
 taxi-ms:
   image: taxi-ms:1.0
   container_name: taxi-ms
   ports:
     - 8080:8080

